### ISSUE TITLE
attributes have wrong structure

### ISSUE THREAD

**Issue by pvgenuchten** [pvgenuchten/pyGeoDataCrawler#29]
current:

```yaml
attributes:
   foo: string
   bar: numeric
```

target:

```yaml
    attributes:
        - name: foo
          type: string
          units: m
        - name: bar
          type: numeric
          units: K
```
